---
- name: update repo ubuntu
  hosts: myhost
  become: true


  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: install mysql server
      apt:
          name: default-mysql-server
          state: latest
          
